title:            Chandu's Blog
tagline:          Chandrahas Aroori's Thoughts.
description:      Blog full of Chandu's Ideas and Thoughts!
canonical: http://exorust.github.io

# Owner/author information
owner:
  name:           Chandrahas Aroori
  avatar:         avatar.png
  bio:            "Poet, Enterpreneur, & Coder"
  email:          chandrahas.aroori@gmail.com
  github:         Exorust
  disqus:         exorust-github-io-1
  location:       "Hyderabad, TS"
  # Plug in your disqus shortname!

# Google-analytics
google-analytics:
  id: "UA-151340760-1"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: Chandu Who?
    url: /about
  - title: Posts
    url: /articles
  - title: CV
    url: /resume.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     	Asia/Kolkata
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
